# This file is automatically generated by Jina executor normalizer plugin.
# It is not intended for manual editing.

FROM jinaai/jina:2.0.4-standard

ARG JINA_VERSION

# install the third-party requirements
RUN apt-get update && apt-get install --no-install-recommends -y gcc build-essential git && rm -rf /var/lib/apt/lists/*

# setup the workspace
COPY . /workspace
WORKDIR /workspace

ENTRYPOINT ["jina", "executor", "--uses", "config.yml"]